update  (#5)
* add error message (#1)

* add error messsage for 
```
$ ./search.js -u user -t token -d https://asd.atlassian.net -q text~https://bit.adda.com
TypeError: Cannot read properties of undefined (reading 'map')
    at file:///Users/sad/replacor/search.js:127:50
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

* add verbose table for findings (#3)


* update replaceContent to handle type and titles
* add ignore case flag
* add details of search query to table
* no need to print summary
* add short url

* Update README.md

* Update README.md

* Create dependabot.yml

* Update dependabot.yml

* Update dependabot.yml

* Create codeql-analysis.yml

* Create SECURITY.md

* Update dependabot.yml

* Update dependabot.yml

* add debug  messages (#2)

* add replace
* add error messsage
* update replaceContent to handle type and titles
* add ignore case flag
* add log4j
* add loglevel env var
* add details of search query to table
* add short url